deploymentMode: SingleBinary

loki:
  useTestSchema: true
  auth_enabled: false
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
  # Remove the custom config block entirely - let the chart template handle schema config
  # The chart will automatically use testSchemaConfig when useTestSchema: true
  
  # If you need custom server config, use the structured approach instead:
  server:
    http_listen_port: 3100
  
  ingester:
    wal:
      enabled: false
  
  limits_config:
    retention_period: 720h
    allow_structured_metadata: false

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: hcloud-volumes
    size: 10Gi
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

gateway:
  enabled: true
  replicas: 1

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

memcached:
  enabled: false

resultsCache:
  enabled: false

chunksCache:
  enabled: false
