apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak-operatorgroup
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - keycloak
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: fast
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic